server:
  port: 8090
spring:
  profiles:
    active: dev
  application:
    name: platform
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 1MB
  ############################################################
  #
  # 配置数据源	使用阿里巴巴的durid数据源
  #
  ############################################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cosd
    url: jdbc:mysql://192.168.2.150:3306/cosd?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
    password: cosd@123.com
    connection-properties: config.decrypt=false;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJI/xqbyvpVttxfAKulKeSTIb7tZAGaFcPyTnE2r7AHTQ8kOnqKXDda4u59umt9XBFxi7db28KxeVooB138zuRUCAwEAAQ==
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  mail:
    host: smtp.163.com  # SMTP 服务器地址
    username: 13156050650@163.com  # 发送方邮箱地址
    password: Xiao120315!  # 发送方邮箱登录密码或者授权码
    properties:
      mail.smtp.auth: true  # 开启 SMTP 验证
      mail.smtp.starttls.enable: true  # 开启 Transport Layer Security (TLS) 加密
      mail.smtp.starttls.required: true
      mail.smtp.timeout: 5000  # 连接超时时间
      mail.smtp.connectiontimeout: 5000  # 连接超时时间
rest:
  template:
    connection:
      connect-timeout: 30000
      read-timeout: 30000
logging:
  level:
    root: info
  config: classpath:logback-privacy.xml

#########################################################

# swagger的配置参数

#########################################################
swagger:
  group-Name: COSD
  title: COSD Restful Api
  description: COSD restful test tools
  license: Apache License Version 2.0
  service-version: 1.0
  version: 1.0
  user-name: WeiBingtao
  email: weibingtao@13156050650@163.com
  #    显示指定包下的controller
  base-package: com.sansec.kms.controller
  #    对于url路径的筛选
  antPath:
  parameter-name: Authorization
  parameter-type: string
  parameter-description: token
  type: header


