server:
  port: 8080
nacos:
  config:
    server-addr: 192.168.2.150:8848
    namespace: 46b6b568-e6ae-45ca-baa1-819932fc8947
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
spring:
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8858
        port: 8719
        # nacos配置持久化
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel.json
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
            namespace: 46b6b568-e6ae-45ca-baa1-819932fc8947

    nacos:
      discovery:
        server-addr: 192.168.2.150:8848
        namespace: 46b6b568-e6ae-45ca-baa1-819932fc8947
logging:
  level:
    root: info
