FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_USER nacos
ENV MYSQL_PASSWORD nacos
ENV MYSQL_DATABASE nacos_config
RUN mkdir /sql
RUN chmod -R 777 /tmp /sql
COPY db/dbinit.sql /docker-entrypoint-initdb.d/

COPY db/init.sql /sql/
COPY db/ddl.sql /sql/
COPY db/nacos_config.sql /sql/nacos_config.sql
