version: '3'
services:
  cosd-mysql:
    image: $MYSQL_IMAGE
    container_name: cosd-mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3389:3306"
    networks:
      cosd_net:
        ipv4_address: 172.30.1.14
  cosd-redis:
    image: $REDIS_IMAGE
    container_name: cosd-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      cosd_net:
        ipv4_address: 172.30.1.15
networks:
  cosd_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
