version: '3'
services:
  application:
    image: $APPLICATION_IMAGE
    container_name: application
    restart: always
    environment:
      - TZ=Asia/Shanghai
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.config.location=/applications/application.yml --server.port=8090"
    volumes:
      - ./config/application.yml:/applications/application.yml
      - ./data/:/data/
    ports:
      - "8090:8090"
    networks:
      cosd_net:
        ipv4_address: 172.30.1.14
networks:
  cosd_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
