server:
  port: 8090
spring:
#  profiles:
#    active: dev
  application:
    name: cosd-application
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 1MB

  ############################################################
  #
  # 跨域配置
  #
  ############################################################
  # 允许所有来源跨域请求

  mvc:
    cors:
      allowed-origins: "*"
      # 允许所有请求方式
      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
      # 允许所有请求头
      allowed-headers: "*"

  ############################################################
  #
  # 配置数据源	使用阿里巴巴的durid数据源
  #
  ############################################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cosd
    url: jdbc:mysql://cosd-mysql:3306/cosd?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    password: cosd@123.com
    connection-properties: config.decrypt=false;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJI/xqbyvpVttxfAKulKeSTIb7tZAGaFcPyTnE2r7AHTQ8kOnqKXDda4u59umt9XBFxi7db28KxeVooB138zuRUCAwEAAQ==
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  ############################################################
  #
  # 配置邮箱信息
  #
  ############################################################
  mail:
    host: smtp.office365.com  # SMTP 服务器地址
    port: 587
    username: wbt@chessofstars.io # 发送方邮箱地址
    password: Xiao120315!
    #    username: 13156050650@163.com
    #    password: Xiao120315!
    # 发送方邮箱登录密码或者授权码
    subject: verify your email
    properties:
      mail:
        #        store:
        #          protocol: pop3
        smtp:
          auth: true  # 开启 SMTP 验证
          starttls:
            enable: true  # 开启 Transport Layer Security (TLS) 加密
  #            required: true
  #          port: 587
  #          socketFactory:
  #            port: 587
  #            fallback: false
  ##            class: javax.net.ssl.SSLSocketFactory
  #          connectiontimeout: 30000
  #          timeout: 30000
  #          writetimeout: 30000
  #        debug: false

  ############################################################
  #
  # 配置 redis, 目前主要是用来存放验证码，后面会加入限流队列
  #
  ############################################################
  redis:
    host: cosd-redis
    port: 6379
    timeout: 1000
    password: platform
    poolMaxTotal: 300
    poolMaxIdle: 200
    poolMinIdle: 100
    poolMaxWait: 3

  ############################################################
  #
  # 自定义参数
  #
  #########################################################
  myapp:
    mailNickName: COSD
    tokenTimeOut: 18000000
    slAmount: 400
    clubAmount: 4000
    redisChannel: COSD-Transaction
    cipherKey: 3XIIJHvwPVhG1LgUQx0NTHQQruFsJdcFjMjrOnmayk8

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: org.cos.common.entity
  # 加载所有的 xml 文件
  mapper-locations: classpath*:mapper/**/*.xml

############################################################
#
# rest template 配置
#
#########################################################
rest:
  template:
    connection:
      connect-timeout: 30000
      read-timeout: 30000
  ############################################################
  #
  # 配置 log
  #
  ############################################################
logging:
  level:
    root: INFO
    org.apache.ibatis.mapping: INFO
  config: classpath:logback-prod.xml


#########################################################

# swagger的配置参数

#########################################################
swagger:
  group-Name: COSD
  title: COSD Restful Api
  description: COSD restful test tools
  license: Apache License Version 2.0
  service-version: 1.0
  version: 1.0
  user-name: WeiBingtao
  email: weibingtao@13156050650@163.com
  #    显示指定包下的controller
  base-package: org.cos.application.controller
  #    对于url路径的筛选
  antPath:
  parameter-name: Authorization
  parameter-type: string
  parameter-description: token
  type: header

# pagehelper 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql    # 使用参数表达式查询总记录数


web3j:
  bsc:
    client-address: https://endpoints.omniatech.io/v1/bsc/testnet/public
    explorer: https://testnet.bscscan.com/
    contractAddress: "0x401084C7F44f4e2d2945F37bcad2406c24edE223"
    usdtContractAddress: "0x401084C7F44f4e2d2945F37bcad2406c24edE223"
    #    12 个块才能确定一笔交易，3秒出一个块
    blockNumber: 12
    privateKey: 93abdcd7328576f4b477bfef78b30fcfb0c755fb01b8f3ea00804b7d57fb640a
